name: Build & Test

on: [push]

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            include:
              - os: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Build
          shell: bash
          run: ./build.sh

        - name: Test
          shell: bash
          run: go test
        